[package]
authors = ["Giacomo Fenzi <giacomofenzi@outlook.com>"]
edition = "2018"
name = "stabchain"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
num = "0.3"
rand = "0.7"
serde = {version = "1.0", features = ["derive", "rc"]}

[dev-dependencies]
criterion = "0.3"

# Needed as otherwise cargo tries to run benchmarks as tests and messes cmdline args
[lib]
bench = false

[[bench]]
harness = false
name = "entry"
