name: Criterion Benchmark
on: 
  push:
    branches: 
      - master

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      # Install Rust (stable)
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Run benchmark, storing in target/criterion
      - name: Run benchmark
        run: cargo bench -- permutation__random_creation/default/8
      - name: Git Commit 
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            mv target/criterion criterion
            find . ! -name 'criterion' -type d -exec rm -r -f {} +
            git commit -m "Criterion Update" -a
      # Get old benches (if any)
      - name: Push to Branch
        uses: ad-m/github-push-action@master
        with:
            branch: criterion
            force: true
            github_token: ${{ secrets.GITHUB_TOKEN }}
