name: Benchmark
on: ["pull_request"]

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install Rust (stable)
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Run benchmark, storing in output.txt
      - name: Run benchmark
        run: cargo bench -- --output-format bencher | tee output.txt
      # Get old benches (if any)
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1.8.1
        with:
          tool: "cargo"
          output-file-path: output.txt
          fail-on-alert: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-always: true
