name: Full Benchmark
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  benchmark:
    name: Benchmark full testing set
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install Rust (stable)
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Unzip
        run: unzip data.zip -d data/
      - name: Build Release
        run: cargo build --release --example benchmark

      - name: Run Deterministic
        run: cargo run --release --example benchmark -- -m deterministic
      - name: Run IFT
        run: cargo run --release --example benchmark -- -m ift
      - name: Run Shallow
        run: cargo run --release --example benchmark -- -m shallow
